# Site settings
title: MPS Code Rules
email: fedor.isakov@jetbrains.com
description: >- # this means to ignore newlines until "baseurl:"
  Code Rules is a language framework and runtime for running logical
  inference in JetBrains MPS.
baseurl: "/mps-coderules" # the subpath of your site, e.g. /blog
url: "https://jetbrains.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jetbrains_mps
github_username:  jetbrains
time: 2018-09-05
revision: 0.5.0
copyright: JetBrains s.r.o.
copyright_url: "https://jetbrains.com"
homepage: "https://jetbrains.com/mps"
homepage_title: "JetBrains MPS"
github-project: jetbrains/mps-coderules
# Google Analytics
google_analytics: UA-124630631-1

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
mdl_colors: grey-light_blue
plugins:
  - jekyll-feed
  - jekyll-sitemap

include:
  - "content"
  - "img"
  - "_assets"

defaults:
  -
    scope:
      path:            "content/todo/*.md"
    values:
      sitemap:         false

# Exclude from processing.
exclude:
 - "*.gemspec"
 - Gemfile
 - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
